### ISSUE TITLE
Browse Modules Errors with PyTorch 1.2

### ISSUE THREAD

**Issue by samuelwestlake** [Deeplodocus/deeplodocus#244]
The browse modules functionality works as expected with PyTorch v1.0, but not with v1.2.

When loading CrossEntropyLoss without specifying a module, we get an AttributeError that traces back to the get_specific_module function. 

The CrossEntropyLoss can still be imported when the specific module (torch.nn) is specified.

**Comment by Ahleroy** [comment]
Checked with loading Source instances with PyTorch v1.2, no issue so far. I guess a PyTorch module generate issues (just like "torch.nn.parallel.distributed_c10d" with PyTorch 1.0.0)
I will perform additional tests on the losses later.

**Comment by Ahleroy** [comment]
Issue solved by ignoring a PyTorch module when browsing.
